[package]
name = "token_editor"
version = "0.1.0"
authors = ["Felix Kohlgrüber <felix.kohlgrueber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdweb = "0.4.15"
yew = "0.6.0"
rustfmt-nightly = "1.3.3"


# taken from here: https://github.com/project-oak/oak/commit/344577e59878e534f00543a8bd55f5f17bf1d655
[patch.crates-io]
# TODO: Remove when https://github.com/soc/dirs-rs/pull/24 is merged and published.
dirs = { git = "https://github.com/tiziano88/dirs-rs", rev = "ca7572730f6c744a16236e342da60f1205ffc6ec" }
# TODO: Remove when a new version of the term crate is published. The one currently published
# depends on dirs=1.0.2 which means that it does not pick up the fix above, which is done on
# dirs=2.0.1.
term = { git = "https://github.com/Stebalien/term", rev = "11e754980706a53dda998ba5791a203ab3a5f8fa" }